# Setup the environment:
language: ruby
dist: xenial
cache: bundler

before_script:
  - gem update --system
  - gem install bundler

rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - jruby-head
  - ruby-head

env:
  - TZ=UTC
  - TZ=Pacific/Auckland

# Setup the compilers:
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
